server:
  port: 8084
spring:
  application:
    name: airecommendationservice
  data:
    mongodb:
      uri: mongodb://localhost:27017/airecommendationfitnesss
      database: airecommendationfitnesss
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/