server:
  port: 8081
spring:
  application:
    name: userservice
  datasource:
    url: jdbc:h2:mem:fitness-micro-user;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    driver-class-name: org.h2.Driver
    username: sa
    password:
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: true
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/